baseURL: https://helder.uk/
canonifyURLs: false
languageCode: en-uk
title: Helder
theme: "PaperMod"

params:
  description: Daniel Colon's personal blog, where he talks about technology, development, and anything that strikes his fancy.
  ShowReadingTime: True
  ShowShareButtons: False
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/dani%C3%ABl-colon-5b632941/"
    #- name: "gitlab"
    #  url: "https://gitlab.com/dcolon"
    - name: "github"
      url: "https://github.com/djcolon"
    #- name: "discord"
    #  url: "https://discord.com/users/helmusmkii"
  profileMode:
    enabled: true
    title: "Daniel Colon" # optional default will be site title
    subtitle: "Engineer, Architect, Developer"
    imageUrl: "img/portrait_round.png" # optional
    imageTitle: "Daniel Colon" # optional
    imageWidth: 250 # custom size
    imageHeight: 250 # custom size
    buttons:
    - name: About me
      url: "/about"
    - name: Articles
      url: articles
    #- name: Gitlab
    #  url: "https://gitlab.com/dcolon"

menu:
  main:
  - name: articles
    url: /articles/
    weight: 10
  - identifier: categories
    name: categories
    url: /categories/
    weight: 20
  - identifier: tags
    name: tags
    url: /tags/
    weight: 30
